import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { MantineProvider, ColorSchemeScript, mantineHtmlProps } from "@mantine/core";
import { theme } from "@/styles/theme";
import "./globals.css";
import "@mantine/core/styles.css";
import '@mantine/dates/styles.css';

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={`${poppins.variable} antialiased`}>
        <MantineProvider theme={theme}>
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
